dep 'common development' do
  requires 'Java',
           'Groovy',
           'Node.js',
           'ruby',
           'elm',
           'Gradle',
           'Maven',
           'IntelliJ IDEA newest',
           'git',
           'Google Cloud SDK',
           'Kubernetes tools',
           'Koa11y',
           'Docker tools',
           'JSON tools',
           'CSV tools',
           'GitHub tools',
           'Jetty runner',
           'kafkacat',
           'Markdown tools',
           'howdoi'
end
