dep 'common utilities' do
  # TODO install into Utilities dir
  requires 'boot2docker',
           'zsh.managed',
           'git',
           'tig.managed',
           'git-run.npm',
           'git-stats.npm',
           'Glances.pip',
           'htop',
           'vim.managed',
           'docker.managed',
           'prezto',
           'puppet.gem',
           'Packer',
           'jq.managed',
           'the_silver_searcher.managed',
           'Light Table',
           'Beyond Compare',
           'Evernote',
           'Sublime Text',
           'Vagrant',
           'vtop.npm',
           'VirtualBox'
end
